# All video-level tasks joint training (32 GPU training)
# main setting (ConvNext-Large video-level joint training)
_BASE_: "../image_joint_convnext_large.yaml" # all video tasks joint training
DATASETS:
  TEST: ("coco_2017_val",)